### PR TITLE
STOR-752: Change the default StorageClass to the CSI one (GCE)

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-752

- bump(openshift/api): to get CSI migration gates switched off
- bump k8s 1.25 libs to resolve build failures
- [STOR-752](https://issues.redhat.com//browse/STOR-752): Change the default StorageClass to the CSI one

/cc @openshift/storage

### CODE REVIEW

**Comment by ropatil010** [comment]
Platform: GCP
clusterversion: 4.12.0-0.ci.test-2022-09-02-062332-ci-ln-c8ivfm2-lates
Showing atleast 1default sc after removing intree provisioner 
Test for provisioning of volume with types of sc, Showing results below 

rohitpatil@ropatil-mac Downloads % oc get sc
NAME                     PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ssd-csi                  pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   20m
standard-csi (default)   pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   20m

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil -o wide
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   VOLUMEMODE
persistentvolumeclaim/mypvc-csi   Bound    pvc-10090314-b809-4bc2-9ecc-4c52c2f2d331   1Gi        RWO            ssd-csi        34s   Filesystem
NAME                         READY   STATUS    RESTARTS   AGE   IP           NODE                                       NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-jnmwk   1/1     Running   0          26s   10.129.2.7   ci-ln-c8ivfm2-72292-x8q5t-worker-c-fc2gj   <none>           <none>

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil -o wide
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   VOLUMEMODE
persistentvolumeclaim/mypvc-csi   Bound    pvc-03aba9cc-87ae-4a7e-b5a8-dc8ca22e3c0c   1Gi        RWO            standard-csi   28s   Filesystem
NAME                         READY   STATUS    RESTARTS   AGE   IP           NODE                                       NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-2tsvs   1/1     Running   0          23s   10.129.2.8   ci-ln-c8ivfm2-72292-x8q5t-worker-c-fc2gj   <none>           <none>

Working as expected.

**Comment by ropatil010** [comment]
Tested Upgrade scenario and sharing result. Working as expected
Platform: GCP 

rohitpatil@ropatil-mac Downloads % oc get clusterversion
NAME      VERSION                              AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.11.0-0.nightly-2022-09-02-184920   True        False         67m     Cluster version is 4.11.0-0.nightly-2022-09-02-184920

rohitpatil@ropatil-mac Downloads % oc get sc
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ssd-csi              pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   88m
standard (default)   kubernetes.io/gce-pd    Delete          WaitForFirstConsumer   true                   88m
standard-csi         pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   88m

rohitpatil@ropatil-mac Downloads % oc get co storage
NAME      VERSION                              AVAILABLE   PROGRESSING   DEGRADED   SINCE   MESSAGE
storage   4.11.0-0.nightly-2022-09-02-184920   True        False         False      88m      

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil -o wide
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE   VOLUMEMODE
persistentvolumeclaim/mypvc-csi   Bound    pvc-fa92cc31-e2af-4200-8659-025e4a4ca467   1Gi        RWO            standard       33m   Filesystem
NAME                         READY   STATUS    RESTARTS   AGE   IP            NODE                                                         NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-r5c56   1/1     Running   0          33m   10.128.2.31   ropatil-59gcp-s2nqr-worker-a-9gzf5.c.openshift-qe.internal   <none>           <none>

rohitpatil@ropatil-mac Downloads % oc get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
pvc-fa92cc31-e2af-4200-8659-025e4a4ca467   1Gi        RWO            Delete           Bound    testropatil/mypvc-csi   standard                33m

rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-r5c56 -n testropatil /bin/bash -i -- sh -c "echo 'helloworld' > /mnt/storage/testfilegcp.txt" 
rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-r5c56 -n testropatil /bin/bash -i -- sh -c "cat /mnt/storage/testfilegcp.txt"
helloworld

after upgrade 

rohitpatil@ropatil-mac Downloads % oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.ci.test-2022-09-05-065119-ci-ln-y7ndxyk-latest   True        False         56m     Cluster version is 4.12.0-0.ci.test-2022-09-05-065119-ci-ln-y7ndxyk-latest

rohitpatil@ropatil-mac Downloads % oc get sc
NAME                 PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ssd-csi              pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   5h23m
standard (default)   kubernetes.io/gce-pd    Delete          WaitForFirstConsumer   true                   5h24m
standard-csi         pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   5h23m

rohitpatil@ropatil-mac Downloads % oc get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                   STORAGECLASS   REASON   AGE
pvc-fa92cc31-e2af-4200-8659-025e4a4ca467   1Gi        RWO            Delete           Bound    testropatil/mypvc-csi   standard                3h58m

rohitpatil@ropatil-mac Downloads % oc get pvc,pod -n testropatil -o wide
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE     VOLUMEMODE
persistentvolumeclaim/mypvc-csi   Bound    pvc-fa92cc31-e2af-4200-8659-025e4a4ca467   1Gi        RWO            standard       3h58m   Filesystem
NAME                         READY   STATUS    RESTARTS   AGE   IP           NODE                                                         NOMINATED NODE   READINESS GATES
pod/mydep-776f4cb754-2pkdk   1/1     Running   0          80m   10.128.2.4   ropatil-59gcp-s2nqr-worker-a-9gzf5.c.openshift-qe.internal   <none>           <none>

rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-2pkdk -n testropatil /bin/bash -i -- sh -c "cat /mnt/storage/testfilegcp.txt"
helloworld
rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-2pkdk -n testropatil /bin/bash -i -- sh -c "echo 'helloworld' > /mnt/storage/testfilegcp2.txt" 
rohitpatil@ropatil-mac Downloads % oc exec pod/mydep-776f4cb754-2pkdk -n testropatil /bin/bash -i -- sh -c "cat /mnt/storage/testfilegcp2.txt"
helloworld

rohitpatil@ropatil-mac Downloads % oc delete sc standard 
storageclass.storage.k8s.io "standard" deleted
rohitpatil@ropatil-mac Downloads % oc delete sc standard-csi 
storageclass.storage.k8s.io "standard-csi" deleted

rohitpatil@ropatil-mac Downloads % oc get sc
NAME                     PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
ssd-csi                  pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   5h41m
standard-csi (default)   pd.csi.storage.gke.io   Delete          WaitForFirstConsumer   true                   10s

oc get pv -o yaml
Intree: 
    gcePersistentDisk:
      fsType: ext4
      pdName: ropatil-59gcp-s2nqr-dy-pvc-fa92cc31-e2af-4200-8659-025e4a4ca467

CSI: 
  csi:
    driver: pd.csi.storage.gke.io
    fsType: ext4
    volumeAttributes:
      storage.kubernetes.io/csiProvisionerIdentity: 1662367554342-8081-pd.csi.storage.gke.io
    volumeHandle: projects/openshift-qe/zones/us-central1-c/disks/pvc-cbd31f68-3aa6-4975-be50-d99f584f70f7

# After upgrade, test with intree provisioner by creating new pvc,dep 
# After upgrade, test with csi provisioner  

/label qe-approved

**Comment by dobsonj** [comment]
/assign @lpettyjo 
for docs-approved
/assign @mhackett
for px-approved

**Pull request merged**
