### PR TITLE
Revert "STOR-1065: Rework sidecar bindings to bind common ClusterRoles"

### PR DESCRIPTION
**Pull request by neisw**
This reverts commit a582a1f52204c0f63101f7a60003aef5eb3215ea.

Per [OpenShift policy](https://github.com/openshift/enhancements/blob/master/enhancements/release/improving-ci-signal.md#quick-revert), we are reverting this breaking change to get CI and/or nightly payloads flowing again.

[TRT-1158](https://issues.redhat.com/browse/TRT-1158) tracks failures in https://amd64.ocp.releases.ci.openshift.org/releasestream/4.14.0-0.ci/release/4.14.0-0.ci-2023-07-20-162349

Example: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade/1682065683497619456
Show failures for 
[sig-arch] events should not repeat pathologically for ns/openshift-cluster-csi-drivers

Indicating errors such as

`event happened 64 times, something is wrong: ns/openshift-cluster-csi-drivers deployment/gcp-pd-csi-driver-operator hmsg/a2951d9c38 - pathological/true reason/ClusterRoleBindingUpdateFailed Failed to update ClusterRoleBinding.rbac.authorization.k8s.io/gcp-pd-csi-resizer-binding: ClusterRoleBinding.rbac.authorization.k8s.io "gcp-pd-csi-resizer-binding" is invalid: roleRef: Invalid value: rbac.RoleRef{APIGroup:"rbac.authorization.k8s.io", Kind:"ClusterRole", Name:"openshift-csi-main-resizer-role"}: cannot change roleRef From: 18:00:23Z To: 18:00:24Z result=reject `

To unrevert this, revert this PR, and layer an additional separate commit on top that addresses the problem. Before merging the unrevert, please run these jobs on the PR and check the result of (job/X or job/X, test/Y tuple) to confirm the fix has corrected the problem:
/payload 4.14 ci blocking

### CODE REVIEW

**Comment by neisw** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade

**Comment by DennisPeriquet** [comment]
The job run using `/payload-job` above passed with reverting this PR.  [Sippy shows](https://sippy.dptools.openshift.org/sippy-ng/pull_requests/Presubmits?filters=%257B%2522items%2522%253A%255B%257B%2522columnField%2522%253A%2522repo%2522%252C%2522operatorValue%2522%253A%2522equals%2522%252C%2522value%2522%253A%2522gcp-pd-csi-driver-operator%2522%257D%252C%257B%2522columnField%2522%253A%2522number%2522%252C%2522operatorValue%2522%253A%2522equals%2522%252C%2522value%2522%253A%252271%2522%257D%255D%252C%2522linkOperator%2522%253A%2522and%2522%257D) the payload when it was introduced and that payload failed the [gcp aggregated job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/aggregated-gcp-ovn-upgrade-4.14-micro-release-openshift-release-analysis-aggregator/1682065684365840384).

**Comment by dgoodwin** [comment]
Based on feedback from @jsafrane we believe it's best to revert all changes related to this jira that went into the affected payloads.

/label approved
/label jira/valid-bug

**Pull request merged**
