### PR TITLE
GCP PD: Add metrics scraping

### PR DESCRIPTION
**Pull request by jsafrane**
Configure Prometheus to collect GCP PD CSI driver sidecar metrics. The driver itself does not emit any metrics.

WIP: waiting for https://github.com/openshift/library-go/pull/1050

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
for manual tests

**Comment by jsafrane** [comment]
cc @openshift/storage

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by jsafrane** [comment]
/hold cancel
e2e-gcp-csi shows in prometheus:
```
count by(container) (rate(csi_sidecar_operations_seconds_count[1d]))

{container="provisioner-kube-rbac-proxy"} | 9
{container="resizer-kube-rbac-proxy"} | 5
{container="snapshotter-kube-rbac-proxy"} | 7
{container="attacher-kube-rbac-proxy"} | 11

```
I.e. all sidecars reported at least one metric.There is actually lot of them from the CSI tests.

**Pull request merged**
