### PR TITLE
STOR-2052: Enable storage pools

### PR DESCRIPTION
**Pull request by dfajmon**
this is needed for the hyperdisk controller

/cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
Heh, there is no C3 job in the operator repo :-\

**Comment by chao007** [comment]
```
gcloud compute disks describe pvc-dce4b046-6c48-4802-9ef1-db0ddec75299 --zone=us-central1-a --format json
{
  "accessMode": "READ_WRITE_SINGLE",
  "creationTimestamp": "2024-10-20T22:57:40.197-07:00",
  "description": "{\"kubernetes.io/created-for/pv/name\":\"pvc-dce4b046-6c48-4802-9ef1-db0ddec75299\",\"kubernetes.io/created-for/pvc/name\":\"pvc1\",\"kubernetes.io/created-for/pvc/namespace\":\"default\",\"storage.gke.io/created-by\":\"pd.csi.storage.gke.io\"}",
  "enableConfidentialCompute": false,
  "id": "6021442198174192571",
  "kind": "compute#disk",
  "labelFingerprint": "YPtf5ppOKlg=",
  "labels": {
    "kubernetes-io-cluster-chaoyang1021-dt2qj": "owned"
  },
  "name": "pvc-dce4b046-6c48-4802-9ef1-db0ddec75299",
  "physicalBlockSizeBytes": "4096",
  "provisionedIops": "3000",
  "provisionedThroughput": "140",
  "satisfiesPzi": true,
  "selfLink": "https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-a/disks/pvc-dce4b046-6c48-4802-9ef1-db0ddec75299",
  "sizeGb": "6",
  "status": "READY",
  "storagePool": "https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-a/storagePools/pool-us-central1-a",
  "type": "https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-a/diskTypes/hyperdisk-balanced",
  "zone": "https://www.googleapis.com/compute/v1/projects/openshift-qe/zones/us-central1-a"
}
```

**Pull request merged**
